#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-versionomy
Version  : 0.4.4
Release  : 5
URL      : https://rubygems.org/downloads/versionomy-0.4.4.gem
Source0  : https://rubygems.org/downloads/versionomy-0.4.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : ruby
BuildRequires : rubygem-blockenspiel
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
== Versionomy
Versionomy is a generalized version number library.
It provides tools to represent, manipulate, parse, and compare version
numbers in the wide variety of versioning schemes in use.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n versionomy-0.4.4
gem spec %{SOURCE0} -l --ruby > rubygem-versionomy.gemspec

%build
gem build rubygem-versionomy.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
versionomy-0.4.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/versionomy-0.4.4 && ruby -I.:lib test/tc_*.rb && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/versionomy-0.4.4.gem
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Base/convert_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Base/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Base/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Parsing/Builder/cdesc-Builder.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Parsing/Builder/to_generate_parse_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Parsing/Builder/to_modify_original_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Parsing/Builder/to_modify_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Parsing/Builder/to_modify_unparse_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Parsing/cdesc-Parsing.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Parsing/convert_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Parsing/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Rubygems/cdesc-Rubygems.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Rubygems/create_rubygems_to_standard-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Rubygems/create_standard_to_rubygems-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Semver/cdesc-Semver.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Semver/create_semver_to_standard-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/Semver/create_standard_to_semver-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/cdesc-Conversion.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/convert-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/get-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Conversion/register-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/CircularDescendantError/cdesc-CircularDescendantError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/ConversionError/cdesc-ConversionError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/ConversionRedefinedError/cdesc-ConversionRedefinedError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/FormatCreationError/cdesc-FormatCreationError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/FormatRedefinedError/cdesc-FormatRedefinedError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/IllegalValueError/cdesc-IllegalValueError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/ParseError/cdesc-ParseError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/RangeOverlapError/cdesc-RangeOverlapError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/RangeSpecificationError/cdesc-RangeSpecificationError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/SchemaCreationError/cdesc-SchemaCreationError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/SchemaMismatchError/cdesc-SchemaMismatchError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/SymbolRedefinedError/cdesc-SymbolRedefinedError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/TypeMismatchError/cdesc-TypeMismatchError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/UnknownConversionError/cdesc-UnknownConversionError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/UnknownFormatError/cdesc-UnknownFormatError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/UnparseError/cdesc-UnparseError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/VersionomyError/cdesc-VersionomyError.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Errors/cdesc-Errors.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Base/%3d%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Base/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Base/schema-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Base/unparse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Base/unparse_for_serialization-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/AlphabeticIntegerRecognizer/cdesc-AlphabeticIntegerRecognizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/BasicIntegerRecognizer/cdesc-BasicIntegerRecognizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/Builder/cdesc-Builder.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/Builder/default_parse_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/Builder/default_unparse_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/Builder/field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/FieldHandler/cdesc-FieldHandler.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/IntegerFieldBuilder/cdesc-IntegerFieldBuilder.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/IntegerFieldBuilder/recognize_letter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/IntegerFieldBuilder/recognize_number-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/MappingSymbolBuilder/cdesc-MappingSymbolBuilder.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/MappingSymbolBuilder/map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/MappingSymbolRecognizer/cdesc-MappingSymbolRecognizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/RecognizerBase/cdesc-RecognizerBase.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/RegexpStringRecognizer/cdesc-RegexpStringRecognizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/RegexpSymbolRecognizer/cdesc-RegexpSymbolRecognizer.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/StringFieldBuilder/cdesc-StringFieldBuilder.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/StringFieldBuilder/recognize_regexp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/SymbolFieldBuilder/cdesc-SymbolFieldBuilder.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/SymbolFieldBuilder/recognize_regexp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/SymbolFieldBuilder/recognize_regexp_map-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/cdesc-Delimiter.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/default_parse_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/default_unparse_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/modified_copy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/schema-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Delimiter/unparse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Rubygems/ExtraMethods/cdesc-ExtraMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Rubygems/ExtraMethods/parts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Rubygems/ExtraMethods/prerelease%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Rubygems/ExtraMethods/release-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Rubygems/cdesc-Rubygems.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Rubygems/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Semver/ExtraMethods/cdesc-ExtraMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Semver/ExtraMethods/compatible_with%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Semver/ExtraMethods/prerelease%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Semver/ExtraMethods/release-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Semver/cdesc-Semver.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Semver/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Standard/ExtraMethods/cdesc-ExtraMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Standard/ExtraMethods/prerelease%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Standard/ExtraMethods/release-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Standard/cdesc-Standard.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/Standard/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/add_directory-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/canonical_name_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/cdesc-Format.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/get-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/register-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/registered%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/rubygems-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/semver-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Format/standard-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Formats/add_directory-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Formats/canonical_name_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Formats/cdesc-Formats.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Formats/get-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Formats/register-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Formats/registered%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Formats/rubygems-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Formats/semver-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Formats/standard-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Builder/add_module-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Builder/alias_field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Builder/cdesc-Builder.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Builder/default_value_for_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Builder/field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Builder/to_bump_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Builder/to_canonicalize_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Builder/to_compare_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/add_child-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/bump_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/canonicalize_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/cdesc-Field.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/compare_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/default_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/possible_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Field/type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/FieldBuilder/cdesc-FieldBuilder.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/FieldBuilder/default_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/FieldBuilder/field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/FieldBuilder/range-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/FieldBuilder/symbol-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/FieldBuilder/to_bump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/FieldBuilder/to_canonicalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/FieldBuilder/to_compare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/%3d%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/aliases-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/canonical_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/cdesc-Wrapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/field_named-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/modules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/Wrapper/root_field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/cdesc-Schema.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Schema/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/%3c%3d%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/%3e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/bump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/cdesc-Value.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/each_field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/field_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/has_field%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/schema-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/unparse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/unparse_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/values_array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/Value/values_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/cdesc-Versionomy.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/default_format%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/default_format-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/ruby_version-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/semver-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/Versionomy/version_of-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/page-History_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/versionomy-0.4.4/ri/page-Versionomy_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/History.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/Version
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/Versionomy.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/conversion.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/conversion/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/conversion/parsing.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/format.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/format/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/format/delimiter.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/format_definitions/rubygems.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/format_definitions/semver.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/format_definitions/standard.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/interface.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/schema.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/schema/field.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/schema/wrapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/value.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/lib/versionomy/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_custom_format.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_readme_examples.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_rubygems_basic.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_rubygems_conversions.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_semver_basic.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_semver_conversions.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_standard_basic.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_standard_bump.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_standard_change.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_standard_comparison.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_standard_misc.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_standard_parse.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_standard_reset.rb
/usr/lib64/ruby/gems/2.2.0/gems/versionomy-0.4.4/test/tc_version_of.rb
/usr/lib64/ruby/gems/2.2.0/specifications/versionomy-0.4.4.gemspec
