#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-versionomy
Version  : 0.5.0
Release  : 7
URL      : https://rubygems.org/downloads/versionomy-0.5.0.gem
Source0  : https://rubygems.org/downloads/versionomy-0.5.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
== Versionomy
Versionomy is a generalized version number library.
It provides tools to represent, manipulate, parse, and compare version
numbers in the wide variety of versioning schemes in use.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n versionomy-0.5.0
gem spec %{SOURCE0} -l --ruby > rubygem-versionomy.gemspec

%build
gem build rubygem-versionomy.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
versionomy-0.5.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/versionomy-0.4.4 && ruby -I.:lib test/tc_*.rb && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/versionomy-0.5.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/History.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/Version
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/Versionomy.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/conversion.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/conversion/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/conversion/parsing.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/format.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/format/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/format/delimiter.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/format_definitions/rubygems.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/format_definitions/semver.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/format_definitions/standard.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/interface.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/schema.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/schema/field.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/schema/wrapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/value.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/lib/versionomy/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_custom_format.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_readme_examples.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_rubygems_basic.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_rubygems_conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_semver_basic.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_semver_conversions.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_standard_basic.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_standard_bump.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_standard_change.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_standard_comparison.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_standard_misc.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_standard_parse.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_standard_reset.rb
/usr/lib64/ruby/gems/2.3.0/gems/versionomy-0.5.0/test/tc_version_of.rb
/usr/lib64/ruby/gems/2.3.0/specifications/versionomy-0.5.0.gemspec
